### ISSUE TITLE
Can't cycle to another map

### ISSUE THREAD

**Issue by MrTheSharpie** [twizmwazin/CardinalPGM#1003]
Cardinal is up to date, at the moment I'm writing this. 

So the problem is that I start the server and sometimes everything works alright, at first (some other times I appear directly on a survival world...). Then when I /start or setnext and cycle, the real problems start. If I start, the match starts but I'm not on the spawn, I'm just where I was as an obs but with the perms to break blocks. If I cycle, the scoreboard and tab changes but the map doesn't. 

I reverted to the cardinal I had on 1.8 and it worked with no problem... So it's not XML or map problem.

**Comment by TiTo-418** [comment]
Logs? XML?

**Comment by Pablete1234** [comment]
fixed

**Comment by MrTheSharpie** [comment]
@Pablete1234 I'd wait to see if it works before closing it

**Comment by Pablete1234** [comment]
as : https://github.com/twizmwazin/CardinalPGM/wiki/1.9-Update says, download lastest sportbukkit 1.9.2, and lastest cardinal

**Comment by MrTheSharpie** [comment]
Still doesn't work. @TiTo-418 XML is fine because 1) it worked on 1.8 and 2) some of them are from maps.oc.tc.

@Pablete1234 Already did that and still doesn't work.

LOG:
[latest.txt](https://github.com/twizmwazin/CardinalPGM/files/222766/latest.txt)

**Comment by Pablete1234** [comment]
@MrTheSharpie Please, use LASTEST sportbukkit 1.9.2, lastest = the one that is lowest on the ocn repo page

**Comment by MrTheSharpie** [comment]
@Pablete1234 lmao why would they put lastest all the way down

**Comment by Pablete1234** [comment]
@MrTheSharpie just look at the last number in the file, starts at SOMETHING-1.jar, lastest atm is SOMETHING-28.jar

**Comment by MrTheSharpie** [comment]
It works now, thank you
